#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: ./deploy.sh hack [options]

Initialize, validate, and plan the EvoSpaice hack Terraform stack.
The script only deploys when --apply is explicitly provided.

Options:
  --resource-group <name>  Use an explicit Terraform-managed resource group name.
  --backend-config <path>  Backend config file (default: <environment>.tfbackend).
  --var-file <path>        Terraform variable file (default: <environment>.tfvars).
  --apply                  Apply the saved plan after successful validation and planning.
  -h, --help               Show this help.

Examples:
  ./deploy.sh hack
  ./deploy.sh hack --resource-group rg-ai-seq-h3-hack
  ./deploy.sh hack --resource-group rg-ai-seq-h3-hack --apply
EOF
}

if (($# == 0)); then
  usage >&2
  exit 2
fi

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  usage
  exit 0
fi

environment="$1"
shift

resource_group_name=""
backend_config=""
var_file=""
apply_plan=false

while (($# > 0)); do
  case "$1" in
    --resource-group)
      [[ $# -ge 2 ]] || { echo "Missing value for --resource-group." >&2; exit 2; }
      resource_group_name="$2"
      shift 2
      ;;
    --backend-config)
      [[ $# -ge 2 ]] || { echo "Missing value for --backend-config." >&2; exit 2; }
      backend_config="$2"
      shift 2
      ;;
    --var-file)
      [[ $# -ge 2 ]] || { echo "Missing value for --var-file." >&2; exit 2; }
      var_file="$2"
      shift 2
      ;;
    --apply)
      apply_plan=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ "$environment" != "hack" ]]; then
  echo "Only the hack environment is supported." >&2
  exit 2
fi

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
backend_config="${backend_config:-${script_dir}/${environment}.tfbackend}"
var_file="${var_file:-${script_dir}/${environment}.tfvars}"

command -v terraform >/dev/null 2>&1 || {
  echo "Terraform is required but was not found on PATH." >&2
  exit 1
}

for required_file in "$backend_config" "$var_file"; do
  if [[ ! -f "$required_file" ]]; then
    echo "Required file not found: $required_file" >&2
    exit 1
  fi
done

export TF_DATA_DIR="${script_dir}/.terraform/${environment}"
plan_dir="${script_dir}/.tfplans"
plan_file="${plan_dir}/${environment}.tfplan"
mkdir -p "$TF_DATA_DIR" "$plan_dir"

echo "Environment:    $environment"
echo "Backend config: $backend_config"
echo "Variable file:  $var_file"
if [[ -n "$resource_group_name" ]]; then
  echo "Resource group: $resource_group_name"
else
  echo "Resource group: generated by Terraform"
fi

terraform -chdir="$script_dir" init \
  -input=false \
  -reconfigure \
  -backend-config="$backend_config"

terraform -chdir="$script_dir" validate

plan_args=(
  -input=false
  -lock-timeout=5m
  -var-file="$var_file"
  "-var=environment=${environment}"
  -out="$plan_file"
)

if [[ -n "$resource_group_name" ]]; then
  plan_args+=("-var=resource_group_name=${resource_group_name}")
fi

terraform -chdir="$script_dir" plan "${plan_args[@]}"

if [[ "$apply_plan" == true ]]; then
  terraform -chdir="$script_dir" apply -input=false "$plan_file"
else
  echo "Plan saved to $plan_file. Re-run with --apply to deploy it."
fi