services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/ai-sequence-identification:cached
      - ~/.ssh:/home/vscode/.ssh:ro
    stdin_open: true
    tty: true
